#!/bin/bash

echo "Input query for download: "

read input

echo "Input API Key: "

read key

echo "File path: "

read $dir

if [ ! -d $dir ]; then
    echo "Creating file!"
    mkdir $dir
fi

curl -o $dir "http://www.freesound.org/apiv2/search/text/?query=$input&token=$key"

